window.GALLERY_DATA = {
    "categories":  {
                       "gestantes":  [
                                         {
                                             "src":  "img/web/gestantes/IMG_7274.jpg",
                                             "file":  "IMG_7274.jpg.jpeg",
                                             "category":  "gestantes",
                                             "label":  "Gestantes",
                                             "title":  "Vida que floresce",
                                             "phrase":  "Dois corações e uma história inteira.",
                                             "alt":  "Ensaio fotográfico de gestante por Andrieli Guisso Fotografia",
                                             "orientation":  "portrait",
                                             "width":  1571,
                                             "height":  2200
                                         },
                                         {
                                             "src":  "img/web/gestantes/IMG_7234.jpg",
                                             "file":  "IMG_7234.jpg.jpeg",
                                             "category":  "gestantes",
                                             "label":  "Gestantes",
                                             "title":  "Luz da espera",
                                             "phrase":  "Há um universo inteiro crescendo em você.",
                                             "alt":  "Ensaio fotográfico de gestante por Andrieli Guisso Fotografia",
                                             "orientation":  "portrait",
                                             "width":  1571,
                                             "height":  2200
                                         },
                                         {
                                             "src":  "img/web/gestantes/IMG_7168.jpg",
                                             "file":  "IMG_7168.jpg.jpeg",
                                             "category":  "gestantes",
                                             "label":  "Gestantes",
                                             "title":  "Essência materna",
                                             "phrase":  "Há um universo inteiro crescendo em você.",
                                             "alt":  "Ensaio fotográfico de gestante por Andrieli Guisso Fotografia",
                                             "orientation":  "landscape",
                                             "width":  2200,
                                             "height":  1571
                                         },
                                         {
                                             "src":  "img/web/gestantes/IMG_7113.jpg",
                                             "file":  "IMG_7113.jpg.jpeg",
                                             "category":  "gestantes",
                                             "label":  "Gestantes",
                                             "title":  "Amor que cresce",
                                             "phrase":  "Dois corações e uma história inteira.",
                                             "alt":  "Ensaio fotográfico de gestante por Andrieli Guisso Fotografia",
                                             "orientation":  "portrait",
                                             "width":  1571,
                                             "height":  2200
                                         },
                                         {
                                             "src":  "img/web/gestantes/ges9.jpg",
                                             "file":  "ges9.jpeg",
                                             "category":  "gestantes",
                                             "label":  "Gestantes",
                                             "title":  "Vida que floresce",
                                             "phrase":  "Há um universo inteiro crescendo em você.",
                                             "alt":  "Ensaio fotográfico de gestante por Andrieli Guisso Fotografia",
                                             "orientation":  "portrait",
                                             "width":  1571,
                                             "height":  2200
                                         },
                                         {
                                             "src":  "img/web/gestantes/ges8.jpg",
                                             "file":  "ges8.jpeg",
                                             "category":  "gestantes",
                                             "label":  "Gestantes",
                                             "title":  "Doce espera",
                                             "phrase":  "O amor começa antes do primeiro encontro.",
                                             "alt":  "Ensaio fotográfico de gestante por Andrieli Guisso Fotografia",
                                             "orientation":  "landscape",
                                             "width":  2200,
                                             "height":  1571
                                         },
                                         {
                                             "src":  "img/web/gestantes/ges4.jpg",
                                             "file":  "ges4.jpeg",
                                             "category":  "gestantes",
                                             "label":  "Gestantes",
                                             "title":  "Vida que floresce",
                                             "phrase":  "Dois corações e uma história inteira.",
                                             "alt":  "Ensaio fotográfico de gestante por Andrieli Guisso Fotografia",
                                             "orientation":  "portrait",
                                             "width":  1571,
                                             "height":  2200
                                         },
                                         {
                                             "src":  "img/web/gestantes/ges5.jpg",
                                             "file":  "ges5.jpeg",
                                             "category":  "gestantes",
                                             "label":  "Gestantes",
                                             "title":  "Luz da espera",
                                             "phrase":  "Há um universo inteiro crescendo em você.",
                                             "alt":  "Ensaio fotográfico de gestante por Andrieli Guisso Fotografia",
                                             "orientation":  "portrait",
                                             "width":  1571,
                                             "height":  2200
                                         },
                                         {
                                             "src":  "img/web/gestantes/ges2.jpg",
                                             "file":  "ges2.jpeg",
                                             "category":  "gestantes",
                                             "label":  "Gestantes",
                                             "title":  "Novo capítulo",
                                             "phrase":  "O amor começa antes do primeiro encontro.",
                                             "alt":  "Ensaio fotográfico de gestante por Andrieli Guisso Fotografia",
                                             "orientation":  "portrait",
                                             "width":  1571,
                                             "height":  2200
                                         },
                                         {
                                             "src":  "img/web/gestantes/ges1.jpg",
                                             "file":  "ges1.jpeg",
                                             "category":  "gestantes",
                                             "label":  "Gestantes",
                                             "title":  "Amor que cresce",
                                             "phrase":  "Um novo capítulo cresce aqui.",
                                             "alt":  "Ensaio fotográfico de gestante por Andrieli Guisso Fotografia",
                                             "orientation":  "landscape",
                                             "width":  2200,
                                             "height":  1571
                                         },
                                         {
                                             "src":  "img/web/gestantes/IMG_4942.jpg",
                                             "file":  "IMG_4942.jpg.jpeg",
                                             "category":  "gestantes",
                                             "label":  "Gestantes",
                                             "title":  "Doce espera",
                                             "phrase":  "Dois corações e uma história inteira.",
                                             "alt":  "Ensaio fotográfico de gestante por Andrieli Guisso Fotografia",
                                             "orientation":  "landscape",
                                             "width":  2200,
                                             "height":  1571
                                         },
                                         {
                                             "src":  "img/web/gestantes/ges6.jpg",
                                             "file":  "ges6.jpeg",
                                             "category":  "gestantes",
                                             "label":  "Gestantes",
                                             "title":  "Vida que floresce",
                                             "phrase":  "Um novo capítulo cresce aqui.",
                                             "alt":  "Ensaio fotográfico de gestante por Andrieli Guisso Fotografia",
                                             "orientation":  "portrait",
                                             "width":  1571,
                                             "height":  2200
                                         },
                                         {
                                             "src":  "img/web/gestantes/ges7.jpg",
                                             "file":  "ges7.jpeg",
                                             "category":  "gestantes",
                                             "label":  "Gestantes",
                                             "title":  "Luz da espera",
                                             "phrase":  "Há um universo inteiro crescendo em você.",
                                             "alt":  "Ensaio fotográfico de gestante por Andrieli Guisso Fotografia",
                                             "orientation":  "portrait",
                                             "width":  1571,
                                             "height":  2200
                                         },
                                         {
                                             "src":  "img/web/gestantes/ges3.jpg",
                                             "file":  "ges3.jpeg",
                                             "category":  "gestantes",
                                             "label":  "Gestantes",
                                             "title":  "Luz da espera",
                                             "phrase":  "Há um universo inteiro crescendo em você.",
                                             "alt":  "Ensaio fotográfico de gestante por Andrieli Guisso Fotografia",
                                             "orientation":  "portrait",
                                             "width":  1572,
                                             "height":  2200
                                         }
                                     ],
                       "newborn":  [
                                       {
                                           "src":  "img/web/newborn/nb9.jpg",
                                           "file":  "nb9.jpeg",
                                           "category":  "newborn",
                                           "label":  "Newborn",
                                           "title":  "Primeiros dias",
                                           "phrase":  "Toda delicadeza cabe neste instante.",
                                           "alt":  "Ensaio fotográfico newborn por Andrieli Guisso Fotografia",
                                           "orientation":  "landscape",
                                           "width":  2200,
                                           "height":  1571
                                       },
                                       {
                                           "src":  "img/web/newborn/nb8.jpg",
                                           "file":  "nb8.jpeg",
                                           "category":  "newborn",
                                           "label":  "Newborn",
                                           "title":  "Pequena ternura",
                                           "phrase":  "Os primeiros detalhes de uma vida inteira.",
                                           "alt":  "Ensaio fotográfico newborn por Andrieli Guisso Fotografia",
                                           "orientation":  "landscape",
                                           "width":  2200,
                                           "height":  1572
                                       },
                                       {
                                           "src":  "img/web/newborn/nb7.jpg",
                                           "file":  "nb7.jpeg",
                                           "category":  "newborn",
                                           "label":  "Newborn",
                                           "title":  "Aconchego",
                                           "phrase":  "Onde o tempo aprende a ir devagar.",
                                           "alt":  "Ensaio fotográfico newborn por Andrieli Guisso Fotografia",
                                           "orientation":  "landscape",
                                           "width":  2200,
                                           "height":  1571
                                       },
                                       {
                                           "src":  "img/web/newborn/nb6.jpg",
                                           "file":  "nb6.jpeg",
                                           "category":  "newborn",
                                           "label":  "Newborn",
                                           "title":  "Pequena ternura",
                                           "phrase":  "Onde o tempo aprende a ir devagar.",
                                           "alt":  "Ensaio fotográfico newborn por Andrieli Guisso Fotografia",
                                           "orientation":  "portrait",
                                           "width":  1571,
                                           "height":  2200
                                       },
                                       {
                                           "src":  "img/web/newborn/nb5.jpg",
                                           "file":  "nb5.jpeg",
                                           "category":  "newborn",
                                           "label":  "Newborn",
                                           "title":  "Primeiros dias",
                                           "phrase":  "Onde o tempo aprende a ir devagar.",
                                           "alt":  "Ensaio fotográfico newborn por Andrieli Guisso Fotografia",
                                           "orientation":  "portrait",
                                           "width":  1571,
                                           "height":  2200
                                       },
                                       {
                                           "src":  "img/web/newborn/nb4.jpg",
                                           "file":  "nb4.jpeg",
                                           "category":  "newborn",
                                           "label":  "Newborn",
                                           "title":  "Amor sem medida",
                                           "phrase":  "Toda delicadeza cabe neste instante.",
                                           "alt":  "Ensaio fotográfico newborn por Andrieli Guisso Fotografia",
                                           "orientation":  "landscape",
                                           "width":  2200,
                                           "height":  1571
                                       },
                                       {
                                           "src":  "img/web/newborn/nb3.jpg",
                                           "file":  "nb3.jpeg",
                                           "category":  "newborn",
                                           "label":  "Newborn",
                                           "title":  "Aconchego",
                                           "phrase":  "Os primeiros detalhes de uma vida inteira.",
                                           "alt":  "Ensaio fotográfico newborn por Andrieli Guisso Fotografia",
                                           "orientation":  "landscape",
                                           "width":  2200,
                                           "height":  1571
                                       },
                                       {
                                           "src":  "img/web/newborn/nb2.jpg",
                                           "file":  "nb2.jpeg",
                                           "category":  "newborn",
                                           "label":  "Newborn",
                                           "title":  "Novo começo",
                                           "phrase":  "Pequenos gestos, memórias eternas.",
                                           "alt":  "Ensaio fotográfico newborn por Andrieli Guisso Fotografia",
                                           "orientation":  "portrait",
                                           "width":  1571,
                                           "height":  2200
                                       },
                                       {
                                           "src":  "img/web/newborn/nb10.jpg",
                                           "file":  "nb10.jpeg",
                                           "category":  "newborn",
                                           "label":  "Newborn",
                                           "title":  "Aconchego",
                                           "phrase":  "Pequenos gestos, memórias eternas.",
                                           "alt":  "Ensaio fotográfico newborn por Andrieli Guisso Fotografia",
                                           "orientation":  "landscape",
                                           "width":  2200,
                                           "height":  1571
                                       }
                                   ],
                       "retratos":  [
                                        {
                                            "src":  "img/web/retratos/IMG_1367.jpg",
                                            "file":  "IMG_1367.jpg.jpeg",
                                            "category":  "retratos",
                                            "label":  "Retratos",
                                            "title":  "Autenticidade",
                                            "phrase":  "Ser você também é uma forma de arte.",
                                            "alt":  "Retrato fotográfico em estúdio por Andrieli Guisso Fotografia",
                                            "orientation":  "portrait",
                                            "width":  1571,
                                            "height":  2200
                                        },
                                        {
                                            "src":  "img/web/retratos/IMG_1190.jpg",
                                            "file":  "IMG_1190.jpg.jpeg",
                                            "category":  "retratos",
                                            "label":  "Retratos",
                                            "title":  "Essência",
                                            "phrase":  "Ser você também é uma forma de arte.",
                                            "alt":  "Retrato fotográfico em estúdio por Andrieli Guisso Fotografia",
                                            "orientation":  "portrait",
                                            "width":  1572,
                                            "height":  2200
                                        },
                                        {
                                            "src":  "img/web/retratos/IMG_1018.jpg",
                                            "file":  "IMG_1018.jpg.jpeg",
                                            "category":  "retratos",
                                            "label":  "Retratos",
                                            "title":  "Luz própria",
                                            "phrase":  "A beleza mora no que é verdadeiro.",
                                            "alt":  "Retrato fotográfico em estúdio por Andrieli Guisso Fotografia",
                                            "orientation":  "portrait",
                                            "width":  1571,
                                            "height":  2200
                                        },
                                        {
                                            "src":  "img/web/retratos/IMG_1332.jpg",
                                            "file":  "IMG_1332.jpg.jpeg",
                                            "category":  "retratos",
                                            "label":  "Retratos",
                                            "title":  "Luz própria",
                                            "phrase":  "Retratos de quem você é.",
                                            "alt":  "Retrato fotográfico em estúdio por Andrieli Guisso Fotografia",
                                            "orientation":  "portrait",
                                            "width":  1571,
                                            "height":  2200
                                        },
                                        {
                                            "src":  "img/web/retratos/IMG_1096.jpg",
                                            "file":  "IMG_1096.jpg.jpeg",
                                            "category":  "retratos",
                                            "label":  "Retratos",
                                            "title":  "Singular",
                                            "phrase":  "Ser você também é uma forma de arte.",
                                            "alt":  "Retrato fotográfico em estúdio por Andrieli Guisso Fotografia",
                                            "orientation":  "portrait",
                                            "width":  1571,
                                            "height":  2200
                                        },
                                        {
                                            "src":  "img/web/retratos/IMG_0960.jpg",
                                            "file":  "IMG_0960.jpg.jpeg",
                                            "category":  "retratos",
                                            "label":  "Retratos",
                                            "title":  "Elegância",
                                            "phrase":  "A beleza mora no que é verdadeiro.",
                                            "alt":  "Retrato fotográfico em estúdio por Andrieli Guisso Fotografia",
                                            "orientation":  "portrait",
                                            "width":  1571,
                                            "height":  2200
                                        }
                                    ]
                   }
};
