window.GALLERY_DATA = {
    "categories":  {
                       "gestantes":  [
                                         {
                                             "src":  "img/web/gestantes/IMG_1735.jpg",
                                             "file":  "IMG_1735.jpg.jpeg",
                                             "category":  "gestantes",
                                             "label":  "Gestantes",
                                             "title":  "Novo capítulo",
                                             "phrase":  "Na delicadeza da espera, cabem todos os sonhos.",
                                             "alt":  "Ensaio fotográfico de gestante por Andrieli Guisso Fotografia",
                                             "orientation":  "landscape",
                                             "width":  2200,
                                             "height":  1571
                                         },
                                         {
                                             "src":  "img/web/gestantes/IMG_1725.jpg",
                                             "file":  "IMG_1725.jpg.jpeg",
                                             "category":  "gestantes",
                                             "label":  "Gestantes",
                                             "title":  "Doce espera",
                                             "phrase":  "Cada curva conta um pouco desse começo.",
                                             "alt":  "Ensaio fotográfico de gestante por Andrieli Guisso Fotografia",
                                             "orientation":  "portrait",
                                             "width":  1571,
                                             "height":  2200
                                         },
                                         {
                                             "src":  "img/web/gestantes/IMG_1667.jpg",
                                             "file":  "IMG_1667.jpg.jpeg",
                                             "category":  "gestantes",
                                             "label":  "Gestantes",
                                             "title":  "Luz da espera",
                                             "phrase":  "Um novo capítulo cresce aqui.",
                                             "alt":  "Ensaio fotográfico de gestante por Andrieli Guisso Fotografia",
                                             "orientation":  "portrait",
                                             "width":  1571,
                                             "height":  2200
                                         },
                                         {
                                             "src":  "img/web/gestantes/IMG_1536.jpg",
                                             "file":  "IMG_1536.jpg.jpeg",
                                             "category":  "gestantes",
                                             "label":  "Gestantes",
                                             "title":  "Doce espera",
                                             "phrase":  "Há um universo inteiro crescendo em você.",
                                             "alt":  "Ensaio fotográfico de gestante por Andrieli Guisso Fotografia",
                                             "orientation":  "portrait",
                                             "width":  1572,
                                             "height":  2200
                                         },
                                         {
                                             "src":  "img/web/gestantes/IMG_1406.jpg",
                                             "file":  "IMG_1406.jpg.jpeg",
                                             "category":  "gestantes",
                                             "label":  "Gestantes",
                                             "title":  "Antes do encontro",
                                             "phrase":  "Cada curva conta um pouco desse começo.",
                                             "alt":  "Ensaio fotográfico de gestante por Andrieli Guisso Fotografia",
                                             "orientation":  "landscape",
                                             "width":  2200,
                                             "height":  1571
                                         },
                                         {
                                             "src":  "img/web/gestantes/IMG_7274.jpg",
                                             "file":  "IMG_7274.jpg.jpeg",
                                             "category":  "gestantes",
                                             "label":  "Gestantes",
                                             "title":  "Vida que floresce",
                                             "phrase":  "A beleza de gerar um novo mundo.",
                                             "alt":  "Ensaio fotográfico de gestante por Andrieli Guisso Fotografia",
                                             "orientation":  "portrait",
                                             "width":  1571,
                                             "height":  2200
                                         },
                                         {
                                             "src":  "img/web/gestantes/IMG_7234.jpg",
                                             "file":  "IMG_7234.jpg.jpeg",
                                             "category":  "gestantes",
                                             "label":  "Gestantes",
                                             "title":  "Luz da espera",
                                             "phrase":  "A espera mais bonita da vida.",
                                             "alt":  "Ensaio fotográfico de gestante por Andrieli Guisso Fotografia",
                                             "orientation":  "portrait",
                                             "width":  1571,
                                             "height":  2200
                                         },
                                         {
                                             "src":  "img/web/gestantes/IMG_7168.jpg",
                                             "file":  "IMG_7168.jpg.jpeg",
                                             "category":  "gestantes",
                                             "label":  "Gestantes",
                                             "title":  "Essência materna",
                                             "phrase":  "Antes de te conhecer, eu já te amava.",
                                             "alt":  "Ensaio fotográfico de gestante por Andrieli Guisso Fotografia",
                                             "orientation":  "landscape",
                                             "width":  2200,
                                             "height":  1571
                                         },
                                         {
                                             "src":  "img/web/gestantes/IMG_7113.jpg",
                                             "file":  "IMG_7113.jpg.jpeg",
                                             "category":  "gestantes",
                                             "label":  "Gestantes",
                                             "title":  "Amor que cresce",
                                             "phrase":  "Dois corações e uma história inteira.",
                                             "alt":  "Ensaio fotográfico de gestante por Andrieli Guisso Fotografia",
                                             "orientation":  "portrait",
                                             "width":  1571,
                                             "height":  2200
                                         },
                                         {
                                             "src":  "img/web/gestantes/ges9.jpg",
                                             "file":  "ges9.jpeg",
                                             "category":  "gestantes",
                                             "label":  "Gestantes",
                                             "title":  "Vida que floresce",
                                             "phrase":  "O primeiro lar de uma vida é um abraço por dentro.",
                                             "alt":  "Ensaio fotográfico de gestante por Andrieli Guisso Fotografia",
                                             "orientation":  "portrait",
                                             "width":  1571,
                                             "height":  2200
                                         },
                                         {
                                             "src":  "img/web/gestantes/ges8.jpg",
                                             "file":  "ges8.jpeg",
                                             "category":  "gestantes",
                                             "label":  "Gestantes",
                                             "title":  "Doce espera",
                                             "phrase":  "O futuro já tem um lugar nos nossos braços.",
                                             "alt":  "Ensaio fotográfico de gestante por Andrieli Guisso Fotografia",
                                             "orientation":  "landscape",
                                             "width":  2200,
                                             "height":  1571
                                         },
                                         {
                                             "src":  "img/web/gestantes/ges4.jpg",
                                             "file":  "ges4.jpeg",
                                             "category":  "gestantes",
                                             "label":  "Gestantes",
                                             "title":  "Vida que floresce",
                                             "phrase":  "Na delicadeza da espera, cabem todos os sonhos.",
                                             "alt":  "Ensaio fotográfico de gestante por Andrieli Guisso Fotografia",
                                             "orientation":  "portrait",
                                             "width":  1571,
                                             "height":  2200
                                         },
                                         {
                                             "src":  "img/web/gestantes/ges5.jpg",
                                             "file":  "ges5.jpeg",
                                             "category":  "gestantes",
                                             "label":  "Gestantes",
                                             "title":  "Luz da espera",
                                             "phrase":  "Antes de te conhecer, eu já te amava.",
                                             "alt":  "Ensaio fotográfico de gestante por Andrieli Guisso Fotografia",
                                             "orientation":  "portrait",
                                             "width":  1571,
                                             "height":  2200
                                         },
                                         {
                                             "src":  "img/web/gestantes/ges2.jpg",
                                             "file":  "ges2.jpeg",
                                             "category":  "gestantes",
                                             "label":  "Gestantes",
                                             "title":  "Novo capítulo",
                                             "phrase":  "Cada curva conta um pouco desse começo.",
                                             "alt":  "Ensaio fotográfico de gestante por Andrieli Guisso Fotografia",
                                             "orientation":  "portrait",
                                             "width":  1571,
                                             "height":  2200
                                         },
                                         {
                                             "src":  "img/web/gestantes/ges1.jpg",
                                             "file":  "ges1.jpeg",
                                             "category":  "gestantes",
                                             "label":  "Gestantes",
                                             "title":  "Amor que cresce",
                                             "phrase":  "Um coração pertinho do outro, aprendendo a ser família.",
                                             "alt":  "Ensaio fotográfico de gestante por Andrieli Guisso Fotografia",
                                             "orientation":  "landscape",
                                             "width":  2200,
                                             "height":  1571
                                         },
                                         {
                                             "src":  "img/web/gestantes/IMG_4942.jpg",
                                             "file":  "IMG_4942.jpg.jpeg",
                                             "category":  "gestantes",
                                             "label":  "Gestantes",
                                             "title":  "Doce espera",
                                             "phrase":  "Um coração pertinho do outro, aprendendo a ser família.",
                                             "alt":  "Ensaio fotográfico de gestante por Andrieli Guisso Fotografia",
                                             "orientation":  "landscape",
                                             "width":  2200,
                                             "height":  1571
                                         },
                                         {
                                             "src":  "img/web/gestantes/ges6.jpg",
                                             "file":  "ges6.jpeg",
                                             "category":  "gestantes",
                                             "label":  "Gestantes",
                                             "title":  "Vida que floresce",
                                             "phrase":  "Um novo capítulo cresce aqui.",
                                             "alt":  "Ensaio fotográfico de gestante por Andrieli Guisso Fotografia",
                                             "orientation":  "portrait",
                                             "width":  1571,
                                             "height":  2200
                                         },
                                         {
                                             "src":  "img/web/gestantes/ges7.jpg",
                                             "file":  "ges7.jpeg",
                                             "category":  "gestantes",
                                             "label":  "Gestantes",
                                             "title":  "Luz da espera",
                                             "phrase":  "Cada curva conta um pouco desse começo.",
                                             "alt":  "Ensaio fotográfico de gestante por Andrieli Guisso Fotografia",
                                             "orientation":  "portrait",
                                             "width":  1571,
                                             "height":  2200
                                         },
                                         {
                                             "src":  "img/web/gestantes/ges3.jpg",
                                             "file":  "ges3.jpeg",
                                             "category":  "gestantes",
                                             "label":  "Gestantes",
                                             "title":  "Luz da espera",
                                             "phrase":  "A espera mais bonita da vida.",
                                             "alt":  "Ensaio fotográfico de gestante por Andrieli Guisso Fotografia",
                                             "orientation":  "portrait",
                                             "width":  1572,
                                             "height":  2200
                                         }
                                     ],
                       "newborn":  [
                                       {
                                           "src":  "img/web/newborn/nb9.jpg",
                                           "file":  "nb9.jpeg",
                                           "category":  "newborn",
                                           "label":  "Newborn",
                                           "title":  "Primeiros dias",
                                           "phrase":  "O colo onde tudo começa.",
                                           "alt":  "Ensaio fotográfico newborn por Andrieli Guisso Fotografia",
                                           "orientation":  "landscape",
                                           "width":  2200,
                                           "height":  1571
                                       },
                                       {
                                           "src":  "img/web/newborn/nb8.jpg",
                                           "file":  "nb8.jpeg",
                                           "category":  "newborn",
                                           "label":  "Newborn",
                                           "title":  "Pequena ternura",
                                           "phrase":  "Um começo cheio de ternura.",
                                           "alt":  "Ensaio fotográfico newborn por Andrieli Guisso Fotografia",
                                           "orientation":  "landscape",
                                           "width":  2200,
                                           "height":  1572
                                       },
                                       {
                                           "src":  "img/web/newborn/nb7.jpg",
                                           "file":  "nb7.jpeg",
                                           "category":  "newborn",
                                           "label":  "Newborn",
                                           "title":  "Aconchego",
                                           "phrase":  "Dedinhos pequenos, descobertas imensas.",
                                           "alt":  "Ensaio fotográfico newborn por Andrieli Guisso Fotografia",
                                           "orientation":  "landscape",
                                           "width":  2200,
                                           "height":  1571
                                       },
                                       {
                                           "src":  "img/web/newborn/nb6.jpg",
                                           "file":  "nb6.jpeg",
                                           "category":  "newborn",
                                           "label":  "Newborn",
                                           "title":  "Pequena ternura",
                                           "phrase":  "O som da sua respiração virou aconchego.",
                                           "alt":  "Ensaio fotográfico newborn por Andrieli Guisso Fotografia",
                                           "orientation":  "portrait",
                                           "width":  1571,
                                           "height":  2200
                                       },
                                       {
                                           "src":  "img/web/newborn/nb5.jpg",
                                           "file":  "nb5.jpeg",
                                           "category":  "newborn",
                                           "label":  "Newborn",
                                           "title":  "Primeiros dias",
                                           "phrase":  "Chegar ao mundo e encontrar um colo.",
                                           "alt":  "Ensaio fotográfico newborn por Andrieli Guisso Fotografia",
                                           "orientation":  "portrait",
                                           "width":  1571,
                                           "height":  2200
                                       },
                                       {
                                           "src":  "img/web/newborn/nb4.jpg",
                                           "file":  "nb4.jpeg",
                                           "category":  "newborn",
                                           "label":  "Newborn",
                                           "title":  "Amor sem medida",
                                           "phrase":  "Toda delicadeza cabe neste instante.",
                                           "alt":  "Ensaio fotográfico newborn por Andrieli Guisso Fotografia",
                                           "orientation":  "landscape",
                                           "width":  2200,
                                           "height":  1571
                                       },
                                       {
                                           "src":  "img/web/newborn/nb3.jpg",
                                           "file":  "nb3.jpeg",
                                           "category":  "newborn",
                                           "label":  "Newborn",
                                           "title":  "Aconchego",
                                           "phrase":  "Um carinho de cada vez, a vida se apresenta.",
                                           "alt":  "Ensaio fotográfico newborn por Andrieli Guisso Fotografia",
                                           "orientation":  "landscape",
                                           "width":  2200,
                                           "height":  1571
                                       },
                                       {
                                           "src":  "img/web/newborn/nb2.jpg",
                                           "file":  "nb2.jpeg",
                                           "category":  "newborn",
                                           "label":  "Newborn",
                                           "title":  "Novo começo",
                                           "phrase":  "Seu primeiro sono, nossa memória favorita.",
                                           "alt":  "Ensaio fotográfico newborn por Andrieli Guisso Fotografia",
                                           "orientation":  "portrait",
                                           "width":  1571,
                                           "height":  2200
                                       },
                                       {
                                           "src":  "img/web/newborn/nb10.jpg",
                                           "file":  "nb10.jpeg",
                                           "category":  "newborn",
                                           "label":  "Newborn",
                                           "title":  "Aconchego",
                                           "phrase":  "Pequenos gestos, memórias eternas.",
                                           "alt":  "Ensaio fotográfico newborn por Andrieli Guisso Fotografia",
                                           "orientation":  "landscape",
                                           "width":  2200,
                                           "height":  1571
                                       }
                                   ],
                       "retratos":  [
                                        {
                                            "src":  "img/web/retratos/IMG_1367.jpg",
                                            "file":  "IMG_1367.jpg.jpeg",
                                            "category":  "retratos",
                                            "label":  "Retratos",
                                            "title":  "Autenticidade",
                                            "phrase":  "O seu jeito torna este retrato único.",
                                            "alt":  "Retrato fotográfico em estúdio por Andrieli Guisso Fotografia",
                                            "orientation":  "portrait",
                                            "width":  1571,
                                            "height":  2200
                                        },
                                        {
                                            "src":  "img/web/retratos/IMG_1190.jpg",
                                            "file":  "IMG_1190.jpg.jpeg",
                                            "category":  "retratos",
                                            "label":  "Retratos",
                                            "title":  "Essência",
                                            "phrase":  "Ser você também é uma forma de arte.",
                                            "alt":  "Retrato fotográfico em estúdio por Andrieli Guisso Fotografia",
                                            "orientation":  "portrait",
                                            "width":  1572,
                                            "height":  2200
                                        },
                                        {
                                            "src":  "img/web/retratos/IMG_1018.jpg",
                                            "file":  "IMG_1018.jpg.jpeg",
                                            "category":  "retratos",
                                            "label":  "Retratos",
                                            "title":  "Luz própria",
                                            "phrase":  "Um instante para se enxergar com carinho.",
                                            "alt":  "Retrato fotográfico em estúdio por Andrieli Guisso Fotografia",
                                            "orientation":  "portrait",
                                            "width":  1571,
                                            "height":  2200
                                        },
                                        {
                                            "src":  "img/web/retratos/IMG_1332.jpg",
                                            "file":  "IMG_1332.jpg.jpeg",
                                            "category":  "retratos",
                                            "label":  "Retratos",
                                            "title":  "Luz própria",
                                            "phrase":  "Ser você também é uma forma de arte.",
                                            "alt":  "Retrato fotográfico em estúdio por Andrieli Guisso Fotografia",
                                            "orientation":  "portrait",
                                            "width":  1571,
                                            "height":  2200
                                        },
                                        {
                                            "src":  "img/web/retratos/IMG_1096.jpg",
                                            "file":  "IMG_1096.jpg.jpeg",
                                            "category":  "retratos",
                                            "label":  "Retratos",
                                            "title":  "Singular",
                                            "phrase":  "O tempo passa, a expressão permanece.",
                                            "alt":  "Retrato fotográfico em estúdio por Andrieli Guisso Fotografia",
                                            "orientation":  "portrait",
                                            "width":  1571,
                                            "height":  2200
                                        },
                                        {
                                            "src":  "img/web/retratos/IMG_0960.jpg",
                                            "file":  "IMG_0960.jpg.jpeg",
                                            "category":  "retratos",
                                            "label":  "Retratos",
                                            "title":  "Elegância",
                                            "phrase":  "Um olhar, muitas formas de contar quem você é.",
                                            "alt":  "Retrato fotográfico em estúdio por Andrieli Guisso Fotografia",
                                            "orientation":  "portrait",
                                            "width":  1571,
                                            "height":  2200
                                        }
                                    ]
                   },
    "phrases":  {
                    "gestantes":  [
                                      "O amor começa antes do primeiro encontro.",
                                      "Um novo capítulo cresce aqui.",
                                      "A espera mais bonita da vida.",
                                      "Antes de te conhecer, eu já te amava.",
                                      "A beleza de gerar um novo mundo.",
                                      "Dois corações e uma história inteira.",
                                      "Há um universo inteiro crescendo em você.",
                                      "Enquanto você cresce, o amor encontra novos caminhos.",
                                      "O primeiro lar de uma vida é um abraço por dentro.",
                                      "Entre sonhos e descobertas, a gente espera por você.",
                                      "Um instante de espera, uma lembrança para sempre.",
                                      "A vida muda de ritmo para receber você.",
                                      "Cada curva conta um pouco desse começo.",
                                      "O futuro já tem um lugar nos nossos braços.",
                                      "Na delicadeza da espera, cabem todos os sonhos.",
                                      "Ainda faltam os primeiros passos, mas o amor já chegou.",
                                      "Você transforma os dias antes mesmo de nascer.",
                                      "Guardar a espera é lembrar onde tudo começou.",
                                      "Um coração pertinho do outro, aprendendo a ser família."
                                  ],
                    "newborn":  [
                                    "Tão pequeno. Um amor sem medida.",
                                    "Os primeiros detalhes de uma vida inteira.",
                                    "Onde o tempo aprende a ir devagar.",
                                    "Um começo cheio de ternura.",
                                    "Pequenos gestos, memórias eternas.",
                                    "O colo onde tudo começa.",
                                    "Toda delicadeza cabe neste instante.",
                                    "Dedinhos pequenos, descobertas imensas.",
                                    "O mundo pode esperar mais um abraço.",
                                    "Seu primeiro sono, nossa memória favorita.",
                                    "Um carinho de cada vez, a vida se apresenta.",
                                    "Há tanta história nesse pequeno começo.",
                                    "O som da sua respiração virou aconchego.",
                                    "Os dias passam; a ternura fica.",
                                    "Chegar ao mundo e encontrar um colo."
                                ],
                    "retratos":  [
                                     "Sua essência merece ser lembrada.",
                                     "Retratos de quem você é.",
                                     "Presença que atravessa o tempo.",
                                     "A beleza mora no que é verdadeiro.",
                                     "Cada olhar guarda uma história.",
                                     "Ser você também é uma forma de arte.",
                                     "Luz, verdade e tudo o que é só seu.",
                                     "Um instante para se enxergar com carinho.",
                                     "Sua história aparece nos detalhes.",
                                     "O seu jeito torna este retrato único.",
                                     "Um encontro entre a luz e a sua presença.",
                                     "Há beleza em se reconhecer.",
                                     "Cada fase merece o seu retrato.",
                                     "O tempo passa, a expressão permanece.",
                                     "Um olhar, muitas formas de contar quem você é."
                                 ]
                }
};
